### ISSUE TITLE
Audio clip not working.

### ISSUE THREAD

**Issue by robotlegocatman** [stream-pi/essential-actions#74]
The audio clip isn't working when I click it. I specified the MP3 and saved the macro. Is it attempting to play through the non-existent raspberry pi speakers? I don't have any speakers at this time. I would love a option to switch the audio output in the server.

**Comment by ArcAIN6** [comment]
No, when you select the audio file, and save the button, once you click it, it should play through your default audio device (in my case, my headset) if it's not playing, you may need to test the feature with other MP3's to ensure it's not just a corrupted MP3. Other than that, i can only suggest restarting the server, or even your system. If that doesn't work, i have no more advice. 

Also, please add weather or not you're using 1.x version, or 2.0.x-snapshot

**Comment by nagaisa** [comment]
i aslo have this problem on both 1x and 2x, i get the error:
 `SEVERE: Uncaught exception occurred!
com.sun.media.jfxmedia.MediaException: Could not create player!
        at javafx.media@18-ea/com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(Unknown Source)
        at javafx.media@18-ea/com.sun.media.jfxmedia.MediaManager.getPlayer(Unknown Source)
        at javafx.media@18-ea/com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer.play(Unknown Source)
        at javafx.media@18-ea/com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer.clipScheduler(Unknown Source)
        at javafx.media@18-ea/com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer$Enthreaderator.lambda$static$0(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)`
